[wokwi]
version = 1
firmware = '../../.pio/build/megaatmega2560/firmware.hex'
elf = '../../.pio/build/megaatmega2560/firmware.elf'

[megaatmega2560]
frequency = 16000000

[[serial]]
port = "/dev/ttyUSB0"
baud = 9600